version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: chat-website-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chat-website
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: chat-website-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: