services:
  - type: web
    name: chat-website-backend
    env: node
    buildCommand: npm ci --only=production && npm rebuild bcrypt --build-from-source
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health